### ISSUE TITLE
Sample project

### ISSUE THREAD

**Issue by mackignacio** [mayajs/maya#1]
## 📝 Description
It will hard to everyone to use this library if they don't have any sample project that they can start of. We can make a simple project that utilize the basic usage of this library. Like how to make a simple folder structure and simple controller example.

## 📋 Todo:

- [x] Create a sample project folder.
- [x] Create an index.ts
- [x] Create a controller.ts
- [x] Create a app.module.ts

## 🔍 Additional Info
This sample project is a basic implementation of this library.
