### ISSUE TITLE
Database Modules

### ISSUE THREAD

**Issue by Mackignacio** [mayajs/maya#24]
## 📝 Description
It will be great if we have only one place where we can define our database type and database connection on the AppModule. Right now we have the mongoConnection option to connect to MongoDB using mongoose. We need to have a module that can be extends by any database type that has the connect function on it. 

## 📋 Todo:

- [ ] Create Database.ts and Database class
- [ ] Create separate repo for Mongo modules
- [ ] Create Mongo.ts - Decorator for Mongoose Models, Mongo connection and Mongo Schema
- [ ] Extends Database class to Mongo class

## 🔍 Additional Info

All database modules must extend the Database class.
