### ISSUE TITLE
Unit Test

### ISSUE THREAD

**Issue by mackignacio** [mayajs/maya#3]
## 📝 Description
Every good project has a good testing. It will be better if we can implement this early on our development.

## 📋 Todo:

- [x] Add test folder for each **.test.ts files**
- [x] Unit test with [Jest](https://jestjs.io/)
- [x] Add CI (Continuous Integration) preferably [Circle CI](https://circleci.com)

## 🔍 Additional Info
If the function relies on other library we need to make a mock for that library.

**Comment by mackignacio** [comment]
This issue is already done. Locking this conversation.

**Comment by mackignacio** [comment]
Close #49
