### ISSUE TITLE
App Module

### ISSUE THREAD

**Issue by mackignacio** [mayajs/maya#4]
## 📝 Description
App module will be the one to accepts all the server settings. It will use the `App` decorator that decorates all the settings on it. App decorator will accept a settings object. All the settings are list below.

Sample **AppModule** class decorated with **App** and accepts **settings options** interface.
```javascript
@App({
  cors?: boolean; // Enable CORS default false
  logs?: string; // Enable logging OPTIONAL

  // Connect to MongoDB OPTIONAL
  mongoConnection?: { 
    url: string;  // Connection string
    options?: ConnectionOptions | undefined; // Mongoose connect options OPTIONAL
  };

  // Port number where the server will listen
  port: number; // Default 3333

  // List of routes with controllers and middlewares
  routes: Array<{
    callback?: Function; // This call function will be called last
    controllers: Controller[]; // List of Controllers
    middlewares: Function[]; // Middlewares for all the routes i.e. JWT Authentication
    path: string; // Main path of this route
  }>;
})
export class AppModule{};
```
## NOTE:
> Middlewares on the routes array applied for all the controllers. If you want to apply a middleware for a specific route. You can define it on the validations option of the **METHOD DECORATOR**.

Method decorator middleware example:
```javascript
@Post({
    path: "/",
    validations: [ /* middlewares for specific route */ ],
  })
```

## 📋 Todo:
- [x] Create App Decorator
- [x] Add optional CORS
- [x] Add mongoose for MongoDB connection
- [x] Add express for creating server to use in background
- [x] Add morgan for optional logging

## 🔍 Additional Info
For SQL connection and other database type it will be added on the future. For now we are just focusing on MongoDB.
