### ISSUE TITLE
Remove express.js library

### ISSUE THREAD

**Issue by mackignacio** [mayajs/maya#41]
## 📝 Description

Right now MayaJS is using express.js as a routing library under the hood. But this is not bad for us to use it but in the future it is better to have our own routing module for us to scale more. I suggest we need to create a routing library for `@mayajs/core`.

### Updates

Already publish [mayajs/router](https://www.npmjs.com/package/@mayajs/router) on npm. I will update @mayajs/core to use this library and remove express as dependency.

## ⚙️ Component

> `@mayajs/routing`

## 📋 Todo:

- [x] Create a routing library
- [x] Routing must be able to plug over app.module.ts
- [x] Routing must be able to have middlewares like express does
- [x] Routing can handle all types of HTTP METHODS
- [x] Routing can have a default validator (OPTIONAL)
- [ ] Routing can have a default response handler (OPTIONAL)

## 🔍 Additional Info

This feature is vital for the release of version 1.0.0.

**Comment by mackignacio** [comment]
Done
