### ISSUE TITLE
Multiple databases

### ISSUE THREAD

**Issue by mackignacio** [mayajs/maya#42]
## 📝 Description

To cater more developers and users. We need to have a feature to handle multiple databases. Right now mayajs can only handles one database at a time. We need to be able to handle an array of database that can be added on the app.module.ts. This can be only implemented if we can handle external module.

## 📋 Todo:

- [x] `database` param on `app.module.ts` handles array
- [x] Create a Database interface for outside modules
- [x] Create a database handler and database switcher

## 🔍 Additional Info

This feature is vital for the release of `version 1.0.0`.
