### ISSUE TITLE
Root MayaJS class

### ISSUE THREAD

**Issue by mackignacio** [mayajs/maya#5]
## 📝 Description
Maya class will accepts the `AppModule` and bootstrap all the necessary routes and models if any. It also serves as an instance of **Express.app**. It's also responsible for starting and setting up the server and listens to it.

## 📋 Todo:

- [ ] Create Maya class
- [ ] Create bootstrap function
- [ ] Create start function
- [ ] Create use function `This function is for using global middleware that all the routes will use.`

## 🔍 Additional Info

This Maya class will be the root of the server.
