### ISSUE TITLE
Models Decorator

### ISSUE THREAD

**Issue by mackignacio** [mayajs/maya#6]
## 📝 Description
Models decorator accepts a name of a model related to a controller. This will replace the value of the variable it was decorated to the value of the model that has the same name that pass on it. This a collection of models and bootstrapped alongside with all the controllers.

Sample code 
```javascript
@Models()
const model : Model<any, any>;
```

## 📋 Todo:

- [x] Create Models decorator
- [x] Create an object of models
- [x] Map all the model and add it on the model object when bootstrapping
- [x] Models decorator must replace the value of the variable with the correct model name
- [x] Models can be called on anywhere not only inside the controller

## 🔍 Additional Info

This decorator must only work if there is a model defined on the `@Controller()` decorator.
